title: AIRSS Documentation

email: airss@msm.cam.ac.uk
description: >-
  ...
baseurl: 
url: http://airss-docs.github.io
twitter_username: 
github_username: 
minimal_mistakes_skin: "air"
logo: "/assets/images/airss-logo.svg"
masthead_title: "&nbsp;"

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5 
paginate_path: /page:num/
timezone: 

plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      lang: en
      base-url: "/"     
  - scope:
      path: zh
    values:
      lang: zh
      base-url: "/zh/"
